#Minecraft server properties
#Fri Jul 24 05:55:51 UTC 2026
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=hard
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=true
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=Reino Olvidado
level-seed=-7573789222461
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=6
max-tick-time=-1
max-world-size=29999984
motd=§8§l» §5§l✦ §d§l✧ REINO OLVIDADO ✧ §5§l✦ §8§l« §r\n§d§l✵ §7Hechizos §8• §c§l⚔ §7balas §8• §2§l☠ §7no-muertos
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=20
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=8
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=7
white-list=false
